2019-01-02 13:50:23,751 - root - INFO - Database initialized.
2019-01-02 13:50:25,084 - root - INFO - "users" table initialized.
2019-01-02 13:50:25,451 - root - INFO - "skill_categories" table initialized.
2019-01-02 13:50:25,854 - root - INFO - "skills" table initialized.
2019-01-02 13:50:26,433 - root - INFO - "person_skills" table initialized.
2019-01-02 13:50:26,834 - root - INFO - "job_status" table initialized.
2019-01-02 13:50:27,346 - root - INFO - "available_jobs" table initialized.
2019-01-02 13:50:27,792 - root - INFO - "pending_jobs" table initialized.
2019-01-02 14:36:44,113 - root - INFO - Database initialized.
2019-01-02 14:36:44,215 - root - INFO - "users" table initialized.
2019-01-02 14:36:44,216 - root - INFO - "skill_categories" table initialized.
2019-01-02 14:36:44,216 - root - INFO - "skills" table initialized.
2019-01-02 14:36:44,234 - root - INFO - "person_skills" table initialized.
2019-01-02 14:36:44,235 - root - INFO - "job_status" table initialized.
2019-01-02 14:36:44,235 - root - INFO - "available_jobs" table initialized.
2019-01-02 14:36:44,236 - root - INFO - "pending_jobs" table initialized.
2019-01-02 14:36:44,443 - root - ERROR - 1062 (23000): Duplicate entry 'Ari' for key 'username'
Traceback (most recent call last):
  File "/home/yair/anaconda3/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 392, in cmd_query
    raw_as_string=raw_as_string)
_mysql_connector.MySQLInterfaceError: Duplicate entry 'Ari' for key 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yair/Documents/ITC/Hackathon/hackathon6/database_queries.py", line 221, in insert_user_details
    cur.execute(the_query, insert_string)
  File "/home/yair/anaconda3/lib/python3.6/site-packages/mysql/connector/cursor_cext.py", line 266, in execute
    raw_as_string=self._raw_as_string)
  File "/home/yair/anaconda3/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 395, in cmd_query
    sqlstate=exc.sqlstate)
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry 'Ari' for key 'username'
2019-01-02 14:36:44,532 - root - ERROR - 1062 (23000): Duplicate entry 'Ilona' for key 'username'
Traceback (most recent call last):
  File "/home/yair/anaconda3/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 392, in cmd_query
    raw_as_string=raw_as_string)
_mysql_connector.MySQLInterfaceError: Duplicate entry 'Ilona' for key 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yair/Documents/ITC/Hackathon/hackathon6/database_queries.py", line 221, in insert_user_details
    cur.execute(the_query, insert_string)
  File "/home/yair/anaconda3/lib/python3.6/site-packages/mysql/connector/cursor_cext.py", line 266, in execute
    raw_as_string=self._raw_as_string)
  File "/home/yair/anaconda3/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 395, in cmd_query
    sqlstate=exc.sqlstate)
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry 'Ilona' for key 'username'
2019-01-02 14:36:44,535 - root - ERROR - 1062 (23000): Duplicate entry 'Jeremy' for key 'username'
Traceback (most recent call last):
  File "/home/yair/anaconda3/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 392, in cmd_query
    raw_as_string=raw_as_string)
_mysql_connector.MySQLInterfaceError: Duplicate entry 'Jeremy' for key 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yair/Documents/ITC/Hackathon/hackathon6/database_queries.py", line 221, in insert_user_details
    cur.execute(the_query, insert_string)
  File "/home/yair/anaconda3/lib/python3.6/site-packages/mysql/connector/cursor_cext.py", line 266, in execute
    raw_as_string=self._raw_as_string)
  File "/home/yair/anaconda3/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 395, in cmd_query
    sqlstate=exc.sqlstate)
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry 'Jeremy' for key 'username'
2019-01-02 14:36:44,623 - root - ERROR - 1062 (23000): Duplicate entry 'Remy' for key 'username'
Traceback (most recent call last):
  File "/home/yair/anaconda3/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 392, in cmd_query
    raw_as_string=raw_as_string)
_mysql_connector.MySQLInterfaceError: Duplicate entry 'Remy' for key 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yair/Documents/ITC/Hackathon/hackathon6/database_queries.py", line 221, in insert_user_details
    cur.execute(the_query, insert_string)
  File "/home/yair/anaconda3/lib/python3.6/site-packages/mysql/connector/cursor_cext.py", line 266, in execute
    raw_as_string=self._raw_as_string)
  File "/home/yair/anaconda3/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 395, in cmd_query
    sqlstate=exc.sqlstate)
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry 'Remy' for key 'username'
2019-01-02 14:36:44,711 - root - ERROR - 1062 (23000): Duplicate entry 'Yair' for key 'username'
Traceback (most recent call last):
  File "/home/yair/anaconda3/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 392, in cmd_query
    raw_as_string=raw_as_string)
_mysql_connector.MySQLInterfaceError: Duplicate entry 'Yair' for key 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yair/Documents/ITC/Hackathon/hackathon6/database_queries.py", line 221, in insert_user_details
    cur.execute(the_query, insert_string)
  File "/home/yair/anaconda3/lib/python3.6/site-packages/mysql/connector/cursor_cext.py", line 266, in execute
    raw_as_string=self._raw_as_string)
  File "/home/yair/anaconda3/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 395, in cmd_query
    sqlstate=exc.sqlstate)
mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry 'Yair' for key 'username'
